version: "3.1"

services:
  sqlserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: PasswordO1.
    volumes:
      - db_data:/var/opt/mssql
      - ./sql/test_db-setup.sql:/usr/src/app/sql/test_db-setup.sql
      - ./sql/cv2-setup.sql:/usr/src/app/sql/cv2-setup.sql
      - ./sql/tpch-setup.sql:/usr/src/app/sql/tpch-setup.sql

volumes:
  db_data:
