services:
  sqlserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: PasswordO1.
    volumes:
      - db_data:/var/opt/mssql
      - ./docker/sql_setups/test_db-setup.sql:/usr/src/app/sql_setups/test_db-setup.sql
      - ./docker/sql_setups/cv2-setup.sql:/usr/src/app/sql_setups/cv2-setup.sql
      - ./docker/sql_setups/tpch-setup.sql:/usr/src/app/sql_setups/tpch-setup.sql
      - ./docker/sql_setups/tpcc-setup.sql:/usr/src/app/sql_setups/tpcc-setup.sql

volumes:
  db_data:
