package edu.upc.fib.inlab.imp.kse.sql.sqlobjectschema.visitor;

import edu.upc.fib.inlab.imp.kse.sql.sqlobjectschema.*;
import edu.upc.fib.inlab.imp.kse.sql.sqlobjectschema.boolean_expressions.ComparisonPredicate;
import edu.upc.fib.inlab.imp.kse.sql.sqlobjectschema.boolean_expressions.ExistsPredicate;
import edu.upc.fib.inlab.imp.kse.sql.sqlobjectschema.boolean_expressions.NotOperation;
import edu.upc.fib.inlab.imp.kse.sql.sqlobjectschema.boolean_expressions.PredicateOperation;
import edu.upc.fib.inlab.imp.kse.sql.sqlobjectschema.constraints.Check;
import edu.upc.fib.inlab.imp.kse.sql.sqlobjectschema.constraints.ForeignKey;
import edu.upc.fib.inlab.imp.kse.sql.sqlobjectschema.constraints.PrimaryKey;
import edu.upc.fib.inlab.imp.kse.sql.sqlobjectschema.constraints.Unique;
import edu.upc.fib.inlab.imp.kse.sql.sqlobjectschema.relational_expressions.CrossJoin;
import edu.upc.fib.inlab.imp.kse.sql.sqlobjectschema.relational_expressions.OnJoin;
import edu.upc.fib.inlab.imp.kse.sql.sqlobjectschema.relational_expressions.TableExpression;
import edu.upc.fib.inlab.imp.kse.sql.sqlobjectschema.relational_expressions.TableReference;
import edu.upc.fib.inlab.imp.kse.sql.sqlobjectschema.selection_expressions.AliasableSelectItem;
import edu.upc.fib.inlab.imp.kse.sql.sqlobjectschema.selection_expressions.Asterisk;
import edu.upc.fib.inlab.imp.kse.sql.sqlobjectschema.sql_data_types.*;
import edu.upc.fib.inlab.imp.kse.sql.sqlobjectschema.value_expressions.ColumnReference;
import edu.upc.fib.inlab.imp.kse.sql.sqlobjectschema.value_expressions.SQLPrimitiveFloat;
import edu.upc.fib.inlab.imp.kse.sql.sqlobjectschema.value_expressions.SQLPrimitiveInteger;
import edu.upc.fib.inlab.imp.kse.sql.sqlobjectschema.value_expressions.SQLPrimitiveString;

public interface SQLObjectSchemaVisitor {
    <T> T visit(TableExpression te);
    <T> T visit(CrossJoin j);
    <T> T visit(OnJoin j);
    <T> T visit(TableReference tr);
    <T> T visit(ComparisonPredicate cp);
    <T> T visit(ColumnReference cr);
    <T> T visit(PredicateOperation po);
    <T> T visit(Assertion a);
    <T> T visit(View v);
    <T> T visit(NotOperation no);
    <T> T visit(ExistsPredicate ep);
    <T> T visit(SQLPrimitiveInteger d);
    <T> T visit(SQLPrimitiveFloat f);
    <T> T visit(SQLPrimitiveString s);
    <T> T visit(Asterisk a);
    <T> T visit(AliasableSelectItem asi);
    <T> T visit(Table t);
    <T> T visit(SchemaReference sr);
    <T> T visit(Attribute a);
    <T> T visit(Check c);
    <T> T visit(Unique u);
    <T> T visit(PrimaryKey pk);
    <T> T visit(ForeignKey fk);
    <T> T visit(SQLChar c);
    <T> T visit(SQLVarchar v);
    <T> T visit(SQLBit b);
    <T> T visit(SQLInt i);
    <T> T visit(SQLSmallint s);
    <T> T visit(SQLFloat f);
    <T> T visit(SQLReal r);
    <T> T visit(SQLDate d);
    <T> T visit(SQLDoublePrecision dp);
    <T> T visit(SQLNumeric n);
    <T> T visit(SQLDateTime dt);
}
