USE master;
GO
IF DB_ID (N'tpch_db') IS NOT NULL
DROP DATABASE [tpch_db];
GO
CREATE DATABASE [tpch_db];
GO

USE [tpch_db];
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE SCHEMA user_schema
GO
CREATE TABLE [user_schema].[CUSTOMER](
    [C_CUSTKEY] [bigint] NOT NULL,
    [C_NAME] [varchar](25) NULL,
    [C_ADDRESS] [varchar](40) NULL,
    [C_NATIONKEY] [bigint] NOT NULL,
    [C_PHONE] [char](15) NULL,
    [C_ACCTBAL] [decimal](18, 0) NULL,
    [C_MKTSEGMENT] [char](10) NULL,
    [C_COMMENT] [varchar](117) NULL,
    PRIMARY KEY CLUSTERED
(
[C_CUSTKEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
    ) ON [PRIMARY]
    GO
/****** Object:  Table [dbo].[LINEITEM]    Script Date: 2/2/2022 15:12:07 ******/
    SET ANSI_NULLS ON
    GO
    SET QUOTED_IDENTIFIER ON
    GO
CREATE TABLE [user_schema].[LINEITEM](
    [L_ORDERKEY] [bigint] NOT NULL,
    [L_PARTKEY] [bigint] NOT NULL,
    [L_SUPPKEY] [bigint] NOT NULL,
    [L_LINENUMBER] [int] NOT NULL,
    [L_QUANTITY] [decimal](18, 0) NULL,
    [L_EXTENDEDPRICE] [decimal](18, 0) NULL,
    [L_DISCOUNT] [decimal](18, 0) NULL,
    [L_TAX] [decimal](18, 0) NULL,
    [L_RETURNFLAG] [char](1) NULL,
    [L_LINESTATUS] [char](1) NULL,
    [L_SHIPDATE] [date] NULL,
    [L_COMMITDATE] [date] NULL,
    [L_RECEIPTDATE] [date] NULL,
    [L_SHIPINSTRUCT] [char](25) NULL,
    [L_SHIPMODE] [char](10) NULL,
    [L_COMMENT] [varchar](44) NULL,
    PRIMARY KEY CLUSTERED
(
    [L_ORDERKEY] ASC,
[L_LINENUMBER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
    ) ON [PRIMARY]
    GO
/****** Object:  Table [dbo].[NATION]    Script Date: 2/2/2022 15:12:07 ******/
    SET ANSI_NULLS ON
    GO
    SET QUOTED_IDENTIFIER ON
    GO
CREATE TABLE [user_schema].[NATION](
    [N_NATIONKEY] [bigint] NOT NULL,
    [N_NAME] [char](25) NULL,
    [N_REGIONKEY] [bigint] NOT NULL,
    [N_COMMENT] [varchar](152) NULL,
    PRIMARY KEY CLUSTERED
(
[N_NATIONKEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
    ) ON [PRIMARY]
    GO
/****** Object:  Table [dbo].[ORDERS]    Script Date: 2/2/2022 15:12:07 ******/
    SET ANSI_NULLS ON
    GO
    SET QUOTED_IDENTIFIER ON
    GO
CREATE TABLE [user_schema].[ORDERS](
    [O_ORDERKEY] [bigint] NOT NULL,
    [O_CUSTKEY] [bigint] NOT NULL,
    [O_ORDERSTATUS] [char](1) NULL,
    [O_TOTALPRICE] [decimal](18, 0) NULL,
    [O_ORDERDATE] [date] NULL,
    [O_ORDERPRIORITY] [char](15) NULL,
    [O_CLERK] [char](15) NULL,
    [O_SHIPPRIORITY] [int] NULL,
    [O_COMMENT] [varchar](79) NULL,
    PRIMARY KEY CLUSTERED
(
[O_ORDERKEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
    ) ON [PRIMARY]
    GO
/****** Object:  Table [dbo].[PART]    Script Date: 2/2/2022 15:12:07 ******/
    SET ANSI_NULLS ON
    GO
    SET QUOTED_IDENTIFIER ON
    GO
CREATE TABLE [user_schema].[PART](
    [P_PARTKEY] [bigint] NOT NULL,
    [P_NAME] [varchar](55) NULL,
    [P_MFGR] [char](25) NULL,
    [P_BRAND] [char](10) NULL,
    [P_TYPE] [varchar](25) NULL,
    [P_SIZE] [int] NULL,
    [P_CONTAINER] [char](10) NULL,
    [P_RETAILPRICE] [decimal](18, 0) NULL,
    [P_COMMENT] [varchar](23) NULL,
    PRIMARY KEY CLUSTERED
(
[P_PARTKEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
    ) ON [PRIMARY]
    GO
/****** Object:  Table [dbo].[PARTSUPP]    Script Date: 2/2/2022 15:12:07 ******/
    SET ANSI_NULLS ON
    GO
    SET QUOTED_IDENTIFIER ON
    GO
CREATE TABLE [user_schema].[PARTSUPP](
    [PS_PARTKEY] [bigint] NOT NULL,
    [PS_SUPPKEY] [bigint] NOT NULL,
    [PS_AVAILQTY] [int] NULL,
    [PS_SUPPLYCOST] [decimal](18, 0) NULL,
    [PS_COMMENT] [varchar](199) NULL,
    PRIMARY KEY CLUSTERED
(
    [PS_PARTKEY] ASC,
[PS_SUPPKEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
    ) ON [PRIMARY]
    GO
/****** Object:  Table [dbo].[REGION]    Script Date: 2/2/2022 15:12:07 ******/
    SET ANSI_NULLS ON
    GO
    SET QUOTED_IDENTIFIER ON
    GO
CREATE TABLE [user_schema].[REGION](
    [R_REGIONKEY] [bigint] NOT NULL,
    [R_NAME] [char](25) NULL,
    [R_COMMENT] [varchar](152) NULL,
    PRIMARY KEY CLUSTERED
(
[R_REGIONKEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
    ) ON [PRIMARY]
    GO
/****** Object:  Table [dbo].[SUPPLIER]    Script Date: 2/2/2022 15:12:07 ******/
    SET ANSI_NULLS ON
    GO
    SET QUOTED_IDENTIFIER ON
    GO
CREATE TABLE [user_schema].[SUPPLIER](
    [S_SUPPKEY] [bigint] NOT NULL,
    [S_NAME] [char](25) NULL,
    [S_ADDRESS] [varchar](40) NULL,
    [S_NATIONKEY] [bigint] NOT NULL,
    [S_PHONE] [char](15) NULL,
    [S_ACCTBAL] [decimal](18, 0) NULL,
    [S_COMMENT] [varchar](101) NULL,
    PRIMARY KEY CLUSTERED
(
[S_SUPPKEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
    ) ON [PRIMARY]
    GO
